server:
  port: 9091

scheduling:
  monitor: 0 */10 * * * ?
  filePath: /data/test/
  platmName: ios,h5,android
#  飞书 群机器人 （Custom Bot）
  webhook: https://www.feishu.cn/flow/api/trigger-webhook/f172ddd06840292d541a4aff3f5e192d

es:
  url: http://106.52.90.51:8308/_search