server:
  port: 9091
  address: 0.0.0.0

scheduling:
  monitor: 0 */1 * * * ?
  filePath: /data/test/
  platmName: ios,h5,android
#  飞书 群机器人 （Custom Bot）
  webhook: https://open.feishu.cn/open-apis/bot/v2/hook/b1f664a5-d06b-4d59-a62d-45acb88aca95

es:
  url: http://106.52.90.51:8308/_search

spring:
  mvc:
    view:
      prefix: /
      suffix: .html